# Due to the changes to the build systems actually on the branch integrated, this script will fail on main until merged

name: Cooker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - cooker*
  pull_request: 
    branches:
     - cooker*

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Job1_-_Prepearing_enviornment:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - name: Prepearing enviornment
  #       run: |
  #         git submodule init
  #         git submodule update
  #         sudo add-apt-repository ppa:alexlarsson/flatpak
  #         sudo apt-get update
  #         sudo apt install flatpak flatpak-builder p7zip-full
  #         sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  #         sudo flatpak install -y org.kde.Sdk//5.15-21.08 org.kde.Platform//5.15-21.08 io.qt.qtwebengine.BaseApp/x86_64/5.15-21.08 org.freedesktop.Sdk.Extension.llvm13

  #     - name: cache-cooker
  #       id: cache-cooker
  #       uses: actions/cache@v2
  #       with:
  #         path: ./*flatpak*
  #         key: ${{ runner.os }}-cache

  Job2_-_Downloading_Sources:
    runs-on: ubuntu-latest
    needs: [Job1_-_Prepearing_enviornment]
    steps:
      - name: Downloading sources
        if: steps.cache-cooker.outputs.cache-hit != 'true'
        run: |
          git submodule init
          git submodule update
          sudo add-apt-repository ppa:alexlarsson/flatpak
          sudo apt-get update
          sudo apt install flatpak flatpak-builder p7zip-full
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.kde.Sdk//5.15-21.08 org.kde.Platform//5.15-21.08 io.qt.qtwebengine.BaseApp/x86_64/5.15-21.08 org.freedesktop.Sdk.Extension.llvm13
          sudo flatpak-builder --download-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

      - name: cache-cooker
        id: cache-cooker
        uses: actions/cache@v2
        with:
          path: ./*flatpak*
          key: ${{ runner.os }}-cache

  Job3_-_Building_part_1:
    runs-on: ubuntu-latest
    needs: [Job2_-_Downloading_Sources]
    steps:
      - name: Bulding part 1 - Until RetroArch Cores
        if: steps.cache-cooker.outputs.cache-hit != 'true'
        run: |
          git submodule init
          git submodule update
          sudo add-apt-repository ppa:alexlarsson/flatpak
          sudo apt-get update
          sudo apt install flatpak flatpak-builder p7zip-full
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.kde.Sdk//5.15-21.08 org.kde.Platform//5.15-21.08 io.qt.qtwebengine.BaseApp/x86_64/5.15-21.08 org.freedesktop.Sdk.Extension.llvm13
          sudo flatpak-builder --build-only --stop-at=retroarch-cores --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

      - name: cache-cooker
        id: cache-cooker
        uses: actions/cache@v2
        with:
          path: ./*flatpak*
          key: ${{ runner.os }}-cache

  Job4_-_Building_part_2:
    runs-on: ubuntu-latest
    needs: [Job3_-_Building_part_1]
    steps:
      - name: Bulding part 1 - Until the end
        if: steps.cache-cooker.outputs.cache-hit != 'true'
        run: |
          sudo flatpak-builder --build-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

      - name: cache-cooker
        id: cache-cooker
        uses: actions/cache@v2
        with:
          path: /
          key: ${{ runner.os }}-cache

  Job5_-_Finishing_build:
    runs-on: ubuntu-latest
    needs: [Job4_-_Building_part_2]
    steps:
      - name: Finishing build
        if: steps.cache-cooker.outputs.cache-hit != 'true'
        run: |
          sudo flatpak-builder --finish-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

      - name: cache-cooker
        id: cache-cooker
        uses: actions/cache@v2
        with:
          path: /
          key: ${{ runner.os }}-cache

  Job6_-_Build_bundle:
    runs-on: ubuntu-latest
    needs: [Job5_-_Finishing_build]
    steps:
      - name: Build bundle
        if: steps.cache-cooker.outputs.cache-hit != 'true'
        run: |
          sudo flatpak build-bundle local RetroDECK.flatpak net.retrodeck.retrodeck

      - name: cache-cooker
        id: cache-cooker
        uses: actions/cache@v2
        with:
          path: /
          key: ${{ runner.os }}-cache

  Job7_-_Publishing_flatpak:
    runs-on: ubuntu-latest
    needs: [Job6_-_Build_bundle]
    steps:

    - name: Get date for artifacts
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M')"

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Publish the flatpak in a new cooker release
      if: steps.cache-cooker.outputs.cache-hit != 'true'
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}"
        body: |
          # Release Notes (Cooker)
          This is a cooker snapshot based on the commit: ${{ github.event.repository.full_name }}@${{github.sha}}.
    
          Cooker channel is provided for the community to test fixes and explore new functionality.
          Please DO NOT open issues or ask support on this build.

        artifacts: "RetroDECK.flatpak"
        allowUpdates: true
        prerelease: true
        draft: false
        token: ${{ secrets.TRIGGER_BUILD_TOKEN }}
        repo: RetroDECK-cooker

  # Job8_-_Uploading_cache:
  #   runs-on: ubuntu-latest
  #   needs: [Job7_-_Publishing_flatpak]
  #   steps:
