# Due to the changes to the build systems actually on the branch integrated, this script will fail on main until merged

name: Cooker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - cooker*
  pull_request: 
    branches:
     - cooker*

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Job 1 - Prepearing_enviornment:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Prepearing enviornment
        run: |
          git submodule init
          git submodule update
          sudo add-apt-repository ppa:alexlarsson/flatpak
          sudo apt-get update
          sudo apt install flatpak flatpak-builder p7zip-full
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y org.kde.Sdk//5.15-21.08 org.kde.Platform//5.15-21.08 io.qt.qtwebengine.BaseApp/x86_64/5.15-21.08 org.freedesktop.Sdk.Extension.llvm13

  Job 2 - Downloading_Sources:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading sources
        run: |
          sudo flatpak-builder --download-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

  Job 3 - Building_part_1:
    runs-on: ubuntu-latest
    steps:
      - name: Bulding part 1 - Until RetroArch Cores
        run: |
          sudo flatpak-builder --build-only --stop-at=retroarch-cores --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

  Job 4 - Building_part_2:
    runs-on: ubuntu-latest
    steps:
      - name: Bulding part 1 - Until the end
        run: |
          sudo flatpak-builder --build-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

  Job 5 - Finishing_build:
    runs-on: ubuntu-latest
    steps:
      - name: Finishing build
        run: |
          sudo flatpak-builder --finish-only --user --install --force-clean --repo=local retrodeck-flatpak net.retrodeck.retrodeck.yml

  Job 6 - Build_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Build bundle
        run: |
          sudo flatpak build-bundle local RetroDECK.flatpak net.retrodeck.retrodeck

  Job 7 - Publishing_flatpak:
    runs-on: ubuntu-latest
    steps:

    - name: Get date for artifacts
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M')"

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Publish the flatpak in a new cooker release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}"
        body: |
          # Release Notes (Cooker)
          This is a cooker snapshot based on the commit: ${{ github.event.repository.full_name }}@${{github.sha}}.
    
          Cooker channel is provided for the community to test fixes and explore new functionality.
          Please DO NOT open issues or ask support on this build.

        artifacts: "RetroDECK.flatpak"
        allowUpdates: true
        prerelease: true
        draft: false
        token: ${{ secrets.TRIGGER_BUILD_TOKEN }}
        repo: RetroDECK-cooker
